In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\users\rocha\appdata\roaming\python\python312\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\rocha\appdata\roaming\python\python312\site-packages (from pandas) (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\rocha\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\rocha\appdata\roaming\python\python312\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\rocha\appdata\roaming\python\python312\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\rocha\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\asyncio\base_events.py", line 640, in run_forever
    self._run_once()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\asyncio\base_events.py", line 1992, in _run_once
    handle._run()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
    await result
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\rocha\AppData\Local\Temp\ipykernel_31948\4080736814.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\rocha\AppData\Roaming\Python\Python312\site-packages\pandas\__init__.py", line 39, in <module>
    from pandas.compat import (
  File "C:\Users\rocha\AppData\Roaming\Python\Python312\site-packages\pandas\compat\__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "C:\Users\rocha\AppData\Roaming\Python\Python312\site-packages\pandas\compat\pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\asyncio\base_events.py", line 640, in run_forever
    self._run_once()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\asyncio\base_events.py", line 1992, in _run_once
    handle._run()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
    await result
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\rocha\AppData\Local\Temp\ipykernel_31948\4080736814.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\rocha\AppData\Roaming\Python\Python312\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\rocha\AppData\Roaming\Python\Python312\site-packages\pandas\core\api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "C:\Users\rocha\AppData\Roaming\Python\Python312\site-packages\pandas\core\dtypes\dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

In [2]:
pip install numpy --upgrade

Requirement already satisfied: numpy in c:\users\rocha\appdata\roaming\python\python312\site-packages (2.2.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\asyncio\base_events.py", line 640, in run_forever
    self._run_once()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\asyncio\base_events.py", line 1992, in _run_once
    handle._run()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
    await result
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\rocha\AppData\Local\Temp\ipykernel_27992\4080736814.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\rocha\AppData\Roaming\Python\Python312\site-packages\pandas\__init__.py", line 39, in <module>
    from pandas.compat import (
  File "C:\Users\rocha\AppData\Roaming\Python\Python312\site-packages\pandas\compat\__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "C:\Users\rocha\AppData\Roaming\Python\Python312\site-packages\pandas\compat\pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\asyncio\base_events.py", line 640, in run_forever
    self._run_once()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\asyncio\base_events.py", line 1992, in _run_once
    handle._run()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
    await result
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\rocha\AppData\Local\Temp\ipykernel_27992\4080736814.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\rocha\AppData\Roaming\Python\Python312\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\rocha\AppData\Roaming\Python\Python312\site-packages\pandas\core\api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "C:\Users\rocha\AppData\Roaming\Python\Python312\site-packages\pandas\core\dtypes\dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "C:\Users\rocha\anaconda3\envs\test_env\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

In [3]:
pip install "numpy<2"

Collecting numpy<2
  Downloading numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
Downloading numpy-1.26.4-cp312-cp312-win_amd64.whl (15.5 MB)
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
    --------------------------------------- 0.3/15.5 MB ? eta -:--:--
   -- ------------------------------------- 0.8/15.5 MB 2.8 MB/s eta 0:00:06
   -- ------------------------------------- 1.0/15.5 MB 1.6 MB/s eta 0:00:10
   ---- ----------------------------------- 1.8/15.5 MB 2.1 MB/s eta 0:00:07
   ----- ---------------------------------- 2.1/15.5 MB 2.2 MB/s eta 0:00:07
   ------ --------------------------------- 2.6/15.5 MB 2.2 MB/s eta 0:00:06
   -------- ------------------------------- 3.1/15.5 MB 2.2 MB/s eta 0:00:06
   --------- ------------------------------ 3.7/15.5 MB 2.3 MB/s eta 0:00:06
   ---------- ----------------------------- 4.2/15.5 MB 2.3 MB/s eta 0:00:05
   ------------ --------------------------- 4.7/15.5 MB 2.3 MB/s eta 0:00:05
   ------------- -------------------------- 5.2/15.5 MB 2.3 MB/s eta 0:00:05
   -------------- ------------------------- 5.8/15.5 MB 2.3 MB/s eta 0:00:05
   ---------------- ----------------------- 6.3/15.5 MB 2.4 MB/s eta 0:00:04
   ----------------- ---------------------- 6.8/15.5 MB 2.4 MB/s eta 0:00:04
   ------------------ --------------------- 7.3/15.5 MB 2.4 MB/s eta 0:00:04
   -------------------- ------------------- 7.9/15.5 MB 2.4 MB/s eta 0:00:04
   --------------------- ------------------ 8.4/15.5 MB 2.4 MB/s eta 0:00:04
   ---------------------- ----------------- 8.9/15.5 MB 2.4 MB/s eta 0:00:03
   ----------------------- ---------------- 9.2/15.5 MB 2.4 MB/s eta 0:00:03
   ------------------------- -------------- 9.7/15.5 MB 2.4 MB/s eta 0:00:03
   -------------------------- ------------- 10.2/15.5 MB 2.4 MB/s eta 0:00:03
   --------------------------- ------------ 10.7/15.5 MB 2.4 MB/s eta 0:00:02
   ----------------------------- ---------- 11.3/15.5 MB 2.4 MB/s eta 0:00:02
   ------------------------------ --------- 11.8/15.5 MB 2.4 MB/s eta 0:00:02
   ------------------------------- -------- 12.3/15.5 MB 2.4 MB/s eta 0:00:02
   --------------------------------- ------ 12.8/15.5 MB 2.4 MB/s eta 0:00:02
   ---------------------------------- ----- 13.4/15.5 MB 2.4 MB/s eta 0:00:01
   ----------------------------------- ---- 13.9/15.5 MB 2.4 MB/s eta 0:00:01
   ------------------------------------- -- 14.4/15.5 MB 2.4 MB/s eta 0:00:01
   -------------------------------------- - 14.9/15.5 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  15.5/15.5 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 15.5/15.5 MB 2.4 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.2.2
    Uninstalling numpy-2.2.2:
      Successfully uninstalled numpy-2.2.2
Successfully installed numpy-1.26.4
Note: you may need to restart the kernel to use updated packages.

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\rocha\AppData\Roaming\Python\Python312\site-packages\~umpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\rocha\AppData\Roaming\Python\Python312\site-packages\~umpy'.
  You can safely remove it manually.

In [1]:
import pandas as pd

In [5]:
pd.__version__

'2.2.3'

In [5]:
df=pd.read_csv('green_tripdata_2019-10.csv.gz')

C:\Users\rocha\AppData\Local\Temp\ipykernel_35680\2000685494.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('green_tripdata_2019-10.csv.gz')

In [20]:
pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.10-cp312-cp312-win_amd64.whl.metadata (5.0 kB)
Downloading psycopg2_binary-2.9.10-cp312-cp312-win_amd64.whl (1.2 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ------------------ --------------------- 0.5/1.2 MB 2.1 MB/s eta 0:00:01
   --------------------------- ------------ 0.8/1.2 MB 1.7 MB/s eta 0:00:01
   ------------------------------------ --- 1.0/1.2 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------- 1.2/1.2 MB 1.3 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.10
Note: you may need to restart the kernel to use updated packages.

In [21]:
from sqlalchemy import create_engine

In [22]:
engine =  create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [32]:
engine.connect()

In [33]:
pd.io.sql.get_schema(df, name='yellow_taxi_data')

'CREATE TABLE "yellow_taxi_data" (\n"VendorID" INTEGER,\n  "lpep_pickup_datetime" TIMESTAMP,\n  "lpep_dropoff_datetime" TIMESTAMP,\n  "store_and_fwd_flag" TEXT,\n  "RatecodeID" INTEGER,\n  "PULocationID" INTEGER,\n  "DOLocationID" INTEGER,\n  "passenger_count" INTEGER,\n  "trip_distance" REAL,\n  "fare_amount" REAL,\n  "extra" REAL,\n  "mta_tax" REAL,\n  "tip_amount" REAL,\n  "tolls_amount" REAL,\n  "ehail_fee" REAL,\n  "improvement_surcharge" REAL,\n  "total_amount" REAL,\n  "payment_type" INTEGER,\n  "trip_type" INTEGER,\n  "congestion_surcharge" REAL\n)'

In [34]:
pd.io.sql.get_schema(df, name='yellow_taxi_data')

'CREATE TABLE "yellow_taxi_data" (\n"VendorID" INTEGER,\n  "lpep_pickup_datetime" TIMESTAMP,\n  "lpep_dropoff_datetime" TIMESTAMP,\n  "store_and_fwd_flag" TEXT,\n  "RatecodeID" INTEGER,\n  "PULocationID" INTEGER,\n  "DOLocationID" INTEGER,\n  "passenger_count" INTEGER,\n  "trip_distance" REAL,\n  "fare_amount" REAL,\n  "extra" REAL,\n  "mta_tax" REAL,\n  "tip_amount" REAL,\n  "tolls_amount" REAL,\n  "ehail_fee" REAL,\n  "improvement_surcharge" REAL,\n  "total_amount" REAL,\n  "payment_type" INTEGER,\n  "trip_type" INTEGER,\n  "congestion_surcharge" REAL\n)'

In [35]:
import pandas as pd

In [36]:
df=pd.read_csv('green_tripdata_2019-10.csv.gz', nrows=100)

In [39]:
df

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2,2019-10-01 00:26:02,2019-10-01 00:39:58,N,1,112,196,1,5.88,18.0,0.50,0.5,0.00,0.0,NaN,0.3,19.30,2,1,0.0
1,1,2019-10-01 00:18:11,2019-10-01 00:22:38,N,1,43,263,1,0.80,5.0,3.25,0.5,0.00,0.0,NaN,0.3,9.05,2,1,0.0
2,1,2019-10-01 00:09:31,2019-10-01 00:24:47,N,1,255,228,2,7.50,21.5,0.50,0.5,0.00,0.0,NaN,0.3,22.80,2,1,0.0
3,1,2019-10-01 00:37:40,2019-10-01 00:41:49,N,1,181,181,1,0.90,5.5,0.50,0.5,0.00,0.0,NaN,0.3,6.80,2,1,0.0
4,2,2019-10-01 00:08:13,2019-10-01 00:17:56,N,1,97,188,1,2.52,10.0,0.50,0.5,2.26,0.0,NaN,0.3,13.56,1,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2,2019-10-01 00:02:53,2019-10-01 00:14:32,N,1,126,74,1,3.10,12.0,0.50,0.5,0.00,0.0,NaN,0.3,13.30,1,1,0.0
96,2,2019-10-01 00:18:45,2019-10-01 00:29:23,N,1,42,74,1,1.64,9.5,0.50,0.5,0.00,0.0,NaN,0.3,10.80,2,1,0.0
97,2,2019-10-01 00:41:32,2019-10-01 00:52:51,N,1,75,42,1,3.17,11.5,0.50,0.5,1.50,0.0,NaN,0.3,14.30,1,1,0.0
98,2,2019-10-01 00:36:54,2019-10-01 00:54:20,N,1,92,179,1,5.48,19.5,0.50,0.5,0.00,0.0,NaN,0.3,20.80,2,1,0.0
99,2,2019-10-01 00:21:27,2019-10-01 00:26:59,N,1,129,129,1,1.02,6.0,0.50,0.5,0.00,0.0,NaN,0.3,7.30,2,1,0.0

In [40]:
df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime)
df.lpep_dropoff_datetime = pd.to_datetime(df.lpep_dropoff_datetime)

In [41]:
pd.to_datetime(df.lpep_dropoff_datetime)

0    2019-10-01 00:39:58
1    2019-10-01 00:22:38
2    2019-10-01 00:24:47
3    2019-10-01 00:41:49
4    2019-10-01 00:17:56
             ...
95   2019-10-01 00:14:32
96   2019-10-01 00:29:23
97   2019-10-01 00:52:51
98   2019-10-01 00:54:20
99   2019-10-01 00:26:59
Name: lpep_dropoff_datetime, Length: 100, dtype: datetime64[ns]

In [43]:
print(pd.io.sql.get_schema(df, name='green_taxi_data',con=engine))

CREATE TABLE green_taxi_data (
	"VendorID" BIGINT,
	lpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	lpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	store_and_fwd_flag TEXT,
	"RatecodeID" BIGINT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	ehail_fee FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	payment_type BIGINT,
	trip_type BIGINT,
	congestion_surcharge FLOAT(53)
)

In [45]:
df_iter = pd.read_csv('green_tripdata_2019-10.csv.gz', iterator=True, chunksize=100000)

In [46]:
df = next(df_iter)

In [47]:
len(df)

100000

In [48]:
df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime)
df.lpep_dropoff_datetime = pd.to_datetime(df.lpep_dropoff_datetime)

In [49]:
df

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2,2019-10-01 00:26:02,2019-10-01 00:39:58,N,1,112,196,1,5.88,18.0,0.50,0.5,0.00,0.0,NaN,0.3,19.30,2,1.0,0.00
1,1,2019-10-01 00:18:11,2019-10-01 00:22:38,N,1,43,263,1,0.80,5.0,3.25,0.5,0.00,0.0,NaN,0.3,9.05,2,1.0,0.00
2,1,2019-10-01 00:09:31,2019-10-01 00:24:47,N,1,255,228,2,7.50,21.5,0.50,0.5,0.00,0.0,NaN,0.3,22.80,2,1.0,0.00
3,1,2019-10-01 00:37:40,2019-10-01 00:41:49,N,1,181,181,1,0.90,5.5,0.50,0.5,0.00,0.0,NaN,0.3,6.80,2,1.0,0.00
4,2,2019-10-01 00:08:13,2019-10-01 00:17:56,N,1,97,188,1,2.52,10.0,0.50,0.5,2.26,0.0,NaN,0.3,13.56,1,1.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,2,2019-10-08 15:45:56,2019-10-08 15:54:45,N,1,95,95,1,0.85,7.0,0.00,0.5,0.00,0.0,NaN,0.3,7.80,2,1.0,0.00
99996,2,2019-10-08 15:43:31,2019-10-08 15:50:11,N,1,74,41,1,0.53,6.0,0.00,0.5,0.00,0.0,NaN,0.3,6.80,2,1.0,0.00
99997,2,2019-10-08 15:57:26,2019-10-08 16:17:41,N,1,75,141,1,1.94,13.0,0.00,0.5,2.98,0.0,NaN,0.3,19.53,1,1.0,2.75
99998,2,2019-10-08 14:58:24,2019-10-08 15:03:40,N,1,33,33,1,0.89,6.0,0.00,0.5,1.36,0.0,NaN,0.3,8.16,1,1.0,0.00
99999,2,2019-10-08 15:10:20,2019-10-08 15:17:44,N,1,33,40,1,1.24,7.0,0.00,0.5,0.00,0.0,NaN,0.3,7.80,2,1.0,0.00

In [54]:
df.head(n=0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [55]:
%time df.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

CPU times: total: 4.45 s
Wall time: 12.2 s

1000

In [53]:
df

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2,2019-10-01 00:26:02,2019-10-01 00:39:58,N,1,112,196,1,5.88,18.0,0.50,0.5,0.00,0.0,NaN,0.3,19.30,2,1.0,0.00
1,1,2019-10-01 00:18:11,2019-10-01 00:22:38,N,1,43,263,1,0.80,5.0,3.25,0.5,0.00,0.0,NaN,0.3,9.05,2,1.0,0.00
2,1,2019-10-01 00:09:31,2019-10-01 00:24:47,N,1,255,228,2,7.50,21.5,0.50,0.5,0.00,0.0,NaN,0.3,22.80,2,1.0,0.00
3,1,2019-10-01 00:37:40,2019-10-01 00:41:49,N,1,181,181,1,0.90,5.5,0.50,0.5,0.00,0.0,NaN,0.3,6.80,2,1.0,0.00
4,2,2019-10-01 00:08:13,2019-10-01 00:17:56,N,1,97,188,1,2.52,10.0,0.50,0.5,2.26,0.0,NaN,0.3,13.56,1,1.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,2,2019-10-08 15:45:56,2019-10-08 15:54:45,N,1,95,95,1,0.85,7.0,0.00,0.5,0.00,0.0,NaN,0.3,7.80,2,1.0,0.00
99996,2,2019-10-08 15:43:31,2019-10-08 15:50:11,N,1,74,41,1,0.53,6.0,0.00,0.5,0.00,0.0,NaN,0.3,6.80,2,1.0,0.00
99997,2,2019-10-08 15:57:26,2019-10-08 16:17:41,N,1,75,141,1,1.94,13.0,0.00,0.5,2.98,0.0,NaN,0.3,19.53,1,1.0,2.75
99998,2,2019-10-08 14:58:24,2019-10-08 15:03:40,N,1,33,33,1,0.89,6.0,0.00,0.5,1.36,0.0,NaN,0.3,8.16,1,1.0,0.00
99999,2,2019-10-08 15:10:20,2019-10-08 15:17:44,N,1,33,40,1,1.24,7.0,0.00,0.5,0.00,0.0,NaN,0.3,7.80,2,1.0,0.00

In [58]:
from time import time

In [60]:
#Iteration to create chunk of data, so it will run on loop until iteration stops

In [59]:
while True: 
    t_start = time()
    df = next(df_iter)
    
    df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime)
    df.lpep_dropoff_datetime = pd.to_datetime(df.lpep_dropoff_datetime)
    
    df.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

    t_end = time()

    print('inserted another chunk, took %.3f second' % (t_end - t_start))

inserted another chunk, took 11.485 second

C:\Users\rocha\AppData\Local\Temp\ipykernel_35680\506197074.py:3: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = next(df_iter)

inserted another chunk, took 10.833 second
inserted another chunk, took 7.221 second

StopIteration: